src/Entity/Communal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="communal")
 *
 * @ORM\Entity(repositoryClass="App\Repository\CommunalRepository")
 *
 * @//Gedmo\SoftDeleteable(fieldName="deleted_at", timeAware=false, hardDelete=true)
 */
class Communal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="name", nullable=false, type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(name="unit", nullable=true, type="string")
     */
    private $unit;

    /**
     * @ORM\Column(name="price", type="float", nullable=false)
     *
     * @Assert\Regex(
     *     pattern="/^[0-9]+(\.[0-9]{1,2})?$/u",
     *     match=true,
     *     message="Imput float: 1234.56")
     */
    private $price;

    /**
     * @ORM\Column(name="counter", nullable=true, type="float")
     */
    private $counter;

    /**
     * @ORM\Column(name="quantity", nullable=true, type="float")
     */
    private $quantity;

    /**
     * @ORM\Column(name="period", nullable=true, type="string")
     */
    private $period;

    /**
     * @ORM\Column(name="total", nullable=true, type="float")
     */
    private $total;

    /**
     * @ORM\Column(name="status", nullable=true, type="integer")
     */
    private $status = 0;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="update")
     */
    private $updated_at;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deleted_at", type="datetime", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\Column(name="iddocument", nullable=true, type="string", length=255)
     */
    private $iddocument;

    /**
     * @ORM\Column(name="datedocument", nullable=true, type="datetime")
     */
    private $datedocument;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="communals")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     */
    private $category;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUnit(): ?float
    {
        return $this->unit;
    }

    public function setUnit(float $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCounter(): ?float
    {
        return $this->counter;
    }

    public function setCounter(float $counter): self
    {
        $this->counter = $counter;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(float $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(float $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getIddocument(): ?string
    {
        return $this->iddocument;
    }

    public function setIddocument(string $iddocument): self
    {
        $this->iddocument = $iddocument;

        return $this;
    }

    public function getDatedocument(): ?\DateTimeInterface
    {
        return $this->datedocument;
    }

    public function setDatedocument(?\DateTimeInterface $datedocument): self
    {
        $this->datedocument = $datedocument;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/CommunalType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Communal;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommunalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
            ])
            /*->add('unit', TextType::class, [
                'required' => true,*/
            ->add('unit', HiddenType::class, [
                'required' => false,
            ])
            ->add('price', TextType::class, [
                'required' => true,
            ])
            ->add('counter', TextType::class, [
                'required' => false,
            ])
            ->add('quantity', TextType::class, [
                'required' => false,
            ])
            ->add('period', ChoiceType::class, [
                'required' => true,
                'choices' => [
                    'Jan' => 1,
                    'Feb' => 2,
                    'Mar' => 3,
                    'Apr' => 4,
                    'May' => 5,
                    'Jun' => 6,
                    'Jul' => 7,
                    'Aug' => 8,
                    'Sep' => 9,
                    'Oct' => 10,
                    'Nov' => 11,
                    'Des' => 12,
                ],
            ])
            ->add('total', TextType::class, [
                'required' => false,
            ])
            ->add('status', ChoiceType::class, [
                'required' => true,
                'choices' => [
                    'New' => 0,
                    'Payed' => 1,
                ],
            ])
            ->add('iddocument', TextType::class, [
                'required' => false,
            ])
            ->add('datedocument', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
                //'input' => 'text',
                //'attr' => ['class' => 'js-datepicker'],
                //'html5' => false,
            ])
            /*->add('category', HiddenType::class, [
                'required' => false,
            ])*/
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                /*function(Category $category) {
                    return sprintf('(%d) %s', $category->getId(), $category->getName());
                },*/
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Communal::class,
        ]);
    }
}

src/Controller/CommunalController.php
<?php

namespace App\Controller;

use App\Entity\Communal;
use App\Form\CommunalType;
use App\Repository\CategoryRepository;
use App\Repository\CommunalRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/communal")
 */
class CommunalController extends AbstractController
{
    /**
     * @Route("/", name="communal_index", methods={"GET", "POST"})
     * @param CategoryRepository $categoryRepository
     * @param CommunalRepository $communalRepository
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(CategoryRepository $categoryRepository, CommunalRepository $communalRepository, Request $request, PaginatorInterface $paginator): Response
    {
        if (!empty($request->request->getInt('val'))) {
            $lim = $request->request->getInt('val');
        } else {
            $lim = 10;
        }

        $communal = $communalRepository->findAll();

        $pagination = $paginator->paginate(
            $communal,
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', $lim)
        );

        return $this->render('communal/index.html.twig', [
            'communals' => $pagination,
        ]);
    }

    /**
     * @Route("/new", name="communal_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $communal = new Communal();
        $form = $this->createForm(CommunalType::class, $communal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //dd($form->getData());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($communal);
            $entityManager->flush();

            return $this->redirectToRoute('communal_index');
        }

        return $this->render('communal/new.html.twig', [
            'communal' => $communal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="communal_show", methods={"GET"})
     * @param Communal $communal
     * @return Response
     */
    public function show(Communal $communal): Response
    {
        return $this->render('communal/show.html.twig', [
            'communal' => $communal,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="communal_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Communal $communal
     * @return Response
     */
    public function edit(Request $request, Communal $communal): Response
    {
        $form = $this->createForm(CommunalType::class, $communal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //dd($form->getData());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('communal_index');
        }

        return $this->render('communal/edit.html.twig', [
            'communal' => $communal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="communal_delete", methods={"GET", "DELETE"})
     * @param Request $request
     * @param Communal $communal
     * @return Response
     */
    public function delete(Request $request, Communal $communal): Response
    {
        if ($this->isCsrfTokenValid('delete'.$communal->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($communal);
            $entityManager->flush();
        }

        return $this->redirectToRoute('communal_index');
    }

    /**
     * @Route("/ajax", name="ajax", methods={"POST"})
     * @param CommunalRepository $communalRepository
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function ajax(CommunalRepository $communalRepository, Request $request, PaginatorInterface $paginator): Response
    {
        if (!empty($request->request->getInt('val'))) {
            $lim = $request->request->getInt('val');
        } else {
            $lim = 10;
        }

        $communal = $communalRepository->findAll();

        $pagination = $paginator->paginate(
            $communal,
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', $lim)
        );

        return $this->render('communal/_table.html.twig', [
            'communals' => $pagination,
        ]);
    }

    /**
     * @Route("/search", name="search", methods={"POST"})
     * @param CommunalRepository $communalRepository
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function search(CommunalRepository $communalRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $search = $request->request->get('search');

        if ('' == $search) {
            $communal = $communalRepository->findAll();
        } else {
            $communal = $communalRepository->findBySearchField($search);
        }

        if (!empty($request->request->getInt('val'))) {
            $lim = $request->request->getInt('val');
        } else {
            $lim = 10;
        }

        $pagination = $paginator->paginate(
            $communal,
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', $lim)
        );

        return $this->render('communal/_table.html.twig', [
            'communals' => $pagination,
        ]);
    }
}

templates/communal/_delete_form.html.twig
<form method="post" action="{{ path('communal_delete', {'id': communal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ communal.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/communal/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{#{{ include('communal/_form.html.twig') }}#}
{#{{ include('communal/_form.html.twig', {'button_label': 'Update'}) }}#}

templates/communal/_table.html.twig
<div class="table" id="selected">
    <div class="col-sm-12">
        <table id="selected" class="table table-bordered table-striped dataTable dtr-inline table-hover" role="grid" aria-describedby="example1_info">
            <thead>
            <tr role="row">
                <th>Name *</th>
                <th>Unit</th>
                <th>Price</th>
                <th>Counter</th>
                <th>Quantity</th>
                <th>Period</th>
                <th>Total</th>
                <th># document</th>
                <th>Date document</th>
                <th>Category</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr role="row" class="odd">
                {% for communal in communals %}
                {% if communal.status == 0 %}
            <tr class="{{ '' }}">
                {% elseif communal.status == 1 %}
            <tr class="{{ 'bg-gradient-success' }}">
                {% elseif communal.status == 2 %}
            <tr class="{{ 'bg-gradient-info' }}">
                {% endif %}
                <td>{{ communal.name }}</td>
                <td>{{ communal.unit }}</td>
                <td>{{ communal.price }}</td>
                <td>{{ communal.counter }}</td>
                <td>{{ communal.quantity }}</td>
                <td>{{ communal.period }}</td>
                <td>{{ communal.total }}</td>
                <td>{{ communal.iddocument }}</td>
                <td>{{ communal.datedocument ? communal.datedocument|date('Y-m-d') : ''}}</td>
                <td>{{ communal.category.name }}</td>
                <td>
                    <a href="{{ path('communal_show', {'id': communal.id}) }}"><i class="fa fa-eye" title="Show"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{{ path('communal_edit', {'id': communal.id}) }}"><i class="fa fa-pen" title="Edit"></i></a>
                </td>
            </tr>
            {% else %}
                <tr>
                    <td>no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="col-sm-12 col-md-5" id="getTotalItemCount">
        Total items: {{ communals.getTotalItemCount }}
    </div>
    <div class="col-sm-12 col-md-7">
        <div class="dataTables_paginate paging_simple_numbers" id="knp_pagination_render">
            {{ knp_pagination_render(communals) }}
        </div>
    </div>
</div>

templates/communal/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Invoice{% endblock %}

{% block content %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Invoice</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('main') }}">Home</a></li>
                            <li class="breadcrumb-item active"><a href="{{ path('communal_index') }}">Invoices</a></li>
                            <li class="breadcrumb-item active">Edit invoice</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Edit invoice</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post">
                            <div class="card-body">
                                {{ form_start(form) }}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder': 'fill in the field'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="price">Price</label>
                                    {{ form_widget(form.price, {'attr': {'class': 'form-control', 'placeholder': 'fill in the field'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="counter">Counter</label>
                                    {{ form_widget(form.counter, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="quantity">Quantity</label>
                                    {{ form_widget(form.quantity, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="period">Period</label>
                                    {{ form_widget(form.period, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="total">Total</label>
                                    {{ form_widget(form.total, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    {{ form_widget(form.status, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="iddocument">ID document</label>
                                    {{ form_widget(form.iddocument, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <div class="form-group">
                                    <label for="datedocument">Date document</label>
                                    {{ form_widget(form.datedocument, {'attr': {'class': 'form-control'}} ) }}
                                </div>
                                <div class="form-group">
                                    <label for="categoryId">Category of document</label>
                                    {{ form_widget(form.category, {'attr': {'class': 'form-control'}} ) }}
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">{{ button_label|default('Submit') }}</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{{ path('communal_index') }}">Back to list</a>
                                </div>
                                {{ form_end(form) }}
                                <div class="card-footer">
                                    {{ include('communal/_delete_form.html.twig') }}
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/communal/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Invoices{% endblock %}

{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Invoices</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ path('main') }}">Home</a></li>
                        <li class="breadcrumb-item active">Invoices</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">DataTable of invoices</h3>
                <div class="float-right d-none d-sm-inline-block">
                    <a href="{{ path('communal_new') }}"><i class="fa fa-plus-square" style="font-size: 48px;" title="Add communal"></i></a>
                </div>
            </div>
            <!-- /.card-header -->
            <!-- Card-body -->
            <div class="card-body">
                <div id="" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_length" id="example1_length">
                                <label>Show
                                    <select id="selectData" name="selectData" aria-controls="example1" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="10">10</option>
                                        <option value="25">25</option>
                                        <option value="50">50</option>
                                        <option value="100">100</option>
                                    </select>
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div id="example1_filter" class="dataTables_filter">
                                <label>Search:
                                    <input type="search" id="search" class="form-control form-control-sm" placeholder="Input any text..." aria-controls="example1">
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {{ include('communal/_table.html.twig') }}
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>
    <!-- /.content-wrapper -->
{% endblock %}

templates/communal/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Show Invoice{% endblock %}

{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Invoice</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ path('main') }}">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ path('communal_index') }}">Invoices</a></li>
                        <li class="breadcrumb-item active">Show invoice</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Show invoice</h3>
                    </div>
                    <!-- /.card-header -->
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ communal.id }}</td>
                            </tr>
                            <tr>
                                <th>Name *</th>
                                <td>{{ communal.name }}</td>
                            </tr>
                            <tr>
                                <th>Unit</th>
                                <td>{{ communal.unit }}</td>
                            </tr>
                            <tr>
                                <th>Price</th>
                                <td>{{ communal.price }}</td>
                            </tr>
                            <tr>
                                <th>Counter</th>
                                <td>{{ communal.counter }}</td>
                            </tr>
                            <tr>
                                <th>Quantity</th>
                                <td>{{ communal.quantity }}</td>
                            </tr>
                            <tr>
                                <th>Period</th>
                                <td>{{ communal.period }}</td>
                            </tr>
                            <tr>
                                <th>Total</th>
                                <td>{{ communal.total }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                {% if communal.status == 0 %}
                                <td>{{ 'New' }}</td>
                                {% elseif communal.status == 1 %}
                                <td>{{ 'Payed' }}</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <th>Id document</th>
                                <td>{{ communal.iddocument }}</td>
                            </tr>
                            <tr>
                                <th>Date document</th>
                                <td>{{ communal.datedocument ? communal.datedocument|date('Y-m-d') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Created at</th>
                                <td>{{ communal.createdAt ? communal.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Updated at</th>
                                <td>{{ communal.updatedAt ? communal.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Category</th>
                                <td>{{ communal.category.name }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="card-footer">
                        <a href="{{ path('communal_index') }}">Back to list</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{{ path('communal_edit', {'id': communal.id}) }}">Edit</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                    {% if is_granted('ROLE_ADMIN') %}
                        <div class="card-footer">
                            {{ include('communal/_delete_form.html.twig') }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}